### ISSUE TITLE
Recommend get-pip rather than building Python?

### ISSUE THREAD

**Issue by wence-** [firedrakeproject/isambard#1]
firedrake-install runs get-pip.py https://pip.pypa.io/en/stable/installing/ for systems that don't ship with pip. Is that not sufficient for building?

**Comment by JDBetteridge** [comment]
Cray Python on Isambard has a working pip, neither building Python nor get-pip should be necessary. With some extra work the [alternative_install](https://github.com/firedrakeproject/isambard/tree/alternative_install) branch could be merged.

**Comment by dacreman** [comment]
I've updated the build to use the cray-python module instead of building python.
